### ISSUE TITLE
Version 0.4 pre-release checklist (fix lazy implementation)

### ISSUE THREAD

**Issue by jennydaman** [jennydaman/mindmatter#5]
Minimum viable product completed in 9953bf3053d0f2cb8c572036cbc3607e2975aa31, but there's more to do.

## extension

- [x] Change toggle after cooldown refresh
- [x] rename things: cooldown_date --> cooldown_lock, database --> question_index
- [x] catch notifications permission
- [x] updateDB on 404 error
- [x] improve popup
- [x] https://shields.io/
- [x] multiple right answers client support
- [x] immediately-invoked function expression for app.js
- [x] review options header & blacklist CSS
- [x] fix blacklist click li destroy bug

## gh-pages

- [x] Multiple right answers array in JSON questions
- [x] at least 20 questions
